name: Deploy Blazor to GitHub Pages

on:
  push:
    branches:
      - master  # Change this if your default branch is different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Create or Update githubactions Branch
        run: |
          git checkout -B githubactions
          sed -i 's|href="/"|href="/unnamedgame/"|g' pythonbackendgame/wwwroot/index.html
          sed -i 's|url(/Assets/rainbowcurse.png)|url(/unnamedgame/Assets/rainbowcurse.png)|g' pythonbackendgame/wwwroot/css/app.css
          sed -i 's|url(/Assets/bcurs.png)|url(/unnamedgame/Assets/bcurs.png)|g' pythonbackendgame/wwwroot/css/app.css
          sed -i 's|url(/Assets/rcurs.png)|url(/unnamedgame/Assets/rcurs.png)|g' pythonbackendgame/wwwroot/css/app.css
          sed -i 's|url(/Assets/gcurs.png)|url(/unnamedgame/Assets/gcurs.png)|g' pythonbackendgame/wwwroot/css/app.css
          sed -i 's|url(/Assets/ycurs.png)|url(/unnamedgame/Assets/ycurs.png)|g' pythonbackendgame/wwwroot/css/app.css

          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git commit -am "Update paths for GitHub Pages"
          git push origin githubactions --force

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: '8.0.x' # Adjust if using a different version

      - name: Restore Dependencies
        run: dotnet restore

      - name: Publish Blazor WebAssembly
        run: dotnet publish -c Release -o published --nologo

      - name: Prepare convertedpublish Branch
        run: |
          git checkout --orphan convertedpublish
          git rm -rf .
          mv published/wwwroot/* .
          touch .nojekyll
          git add .
          git commit -m "Deploy Blazor WebAssembly to convertedpublish"
          git push origin convertedpublish --force
